# Site wide configuration

title:            '( )'
locale:           en_UK
url: 'http://kcsongor.github.io'


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Csongor Kiss
  avatar: "https://avatars0.githubusercontent.com/u/313596?v=3&s=460"
  bio: "I like curry"
  email:
  disqus-shortname:
  twitter: lowert #username
  facebook: #username
  google:
    plus: CsongorKiss #username
    analytics: 'UA-10056882-11'
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kcsongor #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: lowertz #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
